### ISSUE TITLE
Shaders don't compile

### ISSUE THREAD

**Issue by mathiassiig** [Facepunch/Facepunch.Highlight#1]
- Open Unity 2018.1.2f1+
- Set build target to iOS
- Drag the materials, shaders and scripts into a folder under Assets/
- See that the materials are magenta due to shader compilation errors

**Comment by mathiassiig** [comment]
Also doesn't work on 2018.1.2f1

**Comment by mathiassiig** [comment]
I don't even know
